version: "3"

services:
  jenkins:
    container_name: jenkins
    image: jenkins-docker
    build:
      context: pipeline
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

  remote_host:
    container_name: remote_host
    image: remote-host
    build:
      context: centos
      dockerfile: Dockerfile
    volumes:
      - $PWD/backup-mysql.sh:/tmp/script.sh
    networks:
      - net

  # db_host:
  #   container_name: db
  #   image: mysql
  #   platform: linux/amd64
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=1234
  #   volumes:
  #     - $PWD/db_data:/var/lib/mysql
  #   networks:
  #     - net
networks:
  net:
